version: "3.1"
services:
  postgres:
    image: postgres:16.1-alpine3.18
    env_file:
      - .env
    volumes:
      - ./src/infraestructure/postgres/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  backend:
    build: .
    network_mode: host
    # depends_on:
    #   postgres:
    #     condition: service_started
    env_file:
      - .env
    ports:
      - 8080:8080
