version: "3.1"
services:
  ddgodeliv-postgres:
    image: postgres:16.1-alpine3.18
    env_file:
      - .env
    volumes:
      - ./src/infraestructure/postgres/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  ddgodeliv-backend:
    build: .
    network_mode: host
    depends_on:
      postgres:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8080:8080"
