@HOST = localhost:8080
@JWT = {{CompanyLoginAPI.response.body.token}}

@JWT_commonuser = {{CommonLoginAPI.response.body.token}}

###
# If user with same email exists, responds with 400 Bad Request
# @name CreateUser
POST http://{{HOST}}/user/
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "password",
    "name": "User User"
}

###
# 400 Bad Request with Errors
# @name CreateUserWithErrors
POST http://{{HOST}}/user
Content-Type: application/json

{
    "email": "",
    "password": "",
    "name": ""
}

###
# 400 Bad Request with Errors
POST http://{{HOST}}/user
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "password",
    "name": "T T"
}

###
# @name CompanyLoginAPI
POST http://{{HOST}}/login/
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

###
# @name CompanyLogout
DELETE http://{{HOST}}/logout/
Authorization: Bearer {{JWT}}

###
# @name CommonLoginAPI
POST http://{{HOST}}/login/
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "password"
}

###
# @name SessionUserInfo
GET http://{{HOST}}/user/
Authorization: Bearer {{JWT}}

###
# @name VehicleListByCompany
GET http://{{HOST}}/vehicle/
Authorization: Bearer {{JWT}}

###
# @name VehicleListByCompany
GET http://{{HOST}}/vehicle/
Authorization: Bearer {{JWT}}

###
# @name VehicleCreateByCompany
POST http://{{HOST}}/vehicle/
Authorization: Bearer {{JWT}}

{
    "license_id": "1281092-12",
    "model_id": 1
}

###
# @name VehicleModelList
GET http://{{HOST}}/vehicle/model/
Authorization: Bearer {{JWT}}

###
# @name VehicleModelCreate
POST http://{{HOST}}/vehicle/model/
Authorization: Bearer {{JWT}}

{
    "name": "207",
    "manufacturer": "Peugeot",
    "year": 2008,
    "max_load": 88
}

###
# @name CompanyCreate
POST http://{{HOST}}/company/
Authorization: Bearer {{JWT}}

{
    "name": "DeliveryCompany",
    "license_id": "fçaksjdfk"
}

###
# @name CompanyDelete
DELETE http://{{HOST}}/company/
Authorization: Bearer {{JWT}}

###
# @name DriverCreate
POST http://{{HOST}}/driver/
Authorization: Bearer {{JWT}}

{
    "license_id": "9897-6xxxp5lkjl",
    "user": {
        "name": "Cristovão Pereira",
        "email": "cristovão@teste.com"
    }
}

###
# @name DriverListByCompany
GET http://{{HOST}}/driver/
Authorization: Bearer {{JWT}}

###
# @name DriverGetOne
GET http://{{HOST}}/driver/4/
Authorization: Bearer {{JWT}}

###
# @name DriverUpdateLicense
PATCH http://{{HOST}}/driver/2/
Authorization: Bearer {{JWT}}

{
    "license_id": "9897987-65565"
}

###
# @name DriverDelete
DELETE http://{{HOST}}/driver/7/
Authorization: Bearer {{JWT}}

###
# @name CommonUserCreateDelivery
POST http://{{HOST}}/delivery/
Authorization: Bearer {{JWT_commonuser}}

{
    "loadout": "Good stuff 2",
    "weight": 77,
    "origin": "A cool place",
    "destination": "Far away",
    "deadline": "2024-03-24T15:04:05Z"
}

###
# @name CommonUserListDeliveriesBySender
GET http://{{HOST}}/delivery/
Authorization: Bearer {{JWT_commonuser}}

###
# @name CommonUserGetDelivery
GET http://{{HOST}}/delivery/1/
Authorization: Bearer {{JWT_commonuser}}

###
# @name CompanyAssignDriverDelivery
PATCH http://{{HOST}}/delivery/5/assign/
Authorization: Bearer {{JWT}}

{
    "driver_id": 5
}

###
# @name CompanyUpdateDeliveryStatus
PATCH http://{{HOST}}/delivery/5/status/
Authorization: Bearer {{JWT}}

{
    "status": 2
}

###
# @name CompanyDelivery
GET http://{{HOST}}/delivery/company/5
Authorization: Bearer {{JWT}}

###
# @name PendingDelivery
GET http://{{HOST}}/delivery/pending/
Authorization: Bearer {{JWT}}

###
# @name DeleteDelivery
DELETE http://{{HOST}}/delivery/1/
Authorization: Bearer {{JWT}}
