@HOST = localhost:8080
@JWT = {{ LoginAPI.response.body.token }}

###
# If user with same email exists, responds with 400 Bad Request
POST http://{{ HOST }}/user
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password",
    "name": "Teste User"
}

###
# 400 Bad Request with Errors
POST http://{{ HOST }}/user
Content-Type: application/json

{
    "email": "",
    "password": "",
    "name": ""
}

###
# @name LoginAPI
POST http://{{ HOST }}/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

###
GET http://{{ HOST }}/user
Authorization: Bearer {{ JWT }}

###
GET http://{{ HOST }}/vehicles/4
Authorization: Bearer {{ JWT }}

###
GET http://{{ HOST }}/vehicles
Authorization: Bearer {{ JWT }}

###
POST http://{{ HOST }}/vehicles
Authorization: Bearer {{ JWT }}

{
    "license_id": "1281092-12",
    "model_id": 1

}

###
GET http://{{ HOST }}/vehicles/model
Authorization: Bearer {{ JWT }}

###
POST http://{{ HOST }}/vehicles/model
Authorization: Bearer {{ JWT }}

{
    "manufacturer": "Peugeot",
    "year": 2008,
    "max_load": 88

}